In [19]:
import pandas as pd
import  numpy as np


# 题目二、按照要求完成以下逻辑回归算法（30分）
# 附件:  Social_Network_Ads.csv  字段如下:
# User_ID –用户编号  Gender –性别（Male—男性, Female---女性
# Age –年龄   EstimatedSalary – 薪水  Purchased—购买（0-不买,1—买）
# 1.导入数据集并划分特征值和标签值 (2分)
#导入数据集
a1=pd.read_csv("E:///python代码/lx-yk/data-yk/yk4/Social_Network_Ads.csv")
# 数据预处理
a1['Gender']=a1['Gender'].map({'Male': 0, 'Female': 1})
# 划分
# 特征值
x=a1[['Gender','Age','EstimatedSalary']]
#标签值
y=a1['Purchased']
# 2.划分测试集和训练集并按照标准差实现特征缩放(3分)

# 特征缩放
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x=scaler.fit_transform(x)# <----------特征缩放

#划分测试集和训练集
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=42)



# 3.使用逻辑回归算法
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter=200)
clf.fit(X_train, y_train)


t4={'solver':['lbfgs', 'liblinear','sag'],'max_iter':[3, 6, 9],'fit_intercept':[True,False]}
from sklearn.model_selection import GridSearchCV
t4_1 = GridSearchCV(clf,t4)
t4_1.fit(X_train, y_train)
print(t4_1.best_params_)#最佳结果
z=t4_1.best_estimator_#最高分
print("最高分",z)

# 5.使用交叉验证实现对模型参数的优化(5分)
train_sizes = np.linspace(0.1,1.0,10)
print(x)

# 6.自主选择使用学习曲线、AUC等模型的可视化 (5分)




# 7.使用最优模型预测数据集，并打印模型特征权重 (5分)

{'fit_intercept': True, 'max_iter': 3, 'solver': 'sag'}
最高分 LogisticRegression(max_iter=3, solver='sag')
[[-1.02020406 -1.78179743 -1.49004624]
 [-1.02020406 -0.25358736 -1.46068138]
 [ 0.98019606 -1.11320552 -0.78528968]
 ...
 [ 0.98019606  1.17910958 -1.46068138]
 [-1.02020406 -0.15807423 -1.07893824]
 [ 0.98019606  1.08359645 -0.99084367]]


D:\Jupyter\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Jupyter\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
