In [ ]:
#索引堆叠的聚合








# Python

In [ ]:

#02 - Python操作数据库

#t.csv

In [ ]:
#3 - Jupyter安装
a=1
a
#04 - Jupyter使用
import  random #随机
a=random.randint(1,6)#随机整数矩阵
print("===",a)

In [ ]:
#05 - Numpy安装
import numpy as npy
#06 - Numpy基本操作
n=npy.array([1,2,3,4])
# n#array([1, 2, 3, 4])
# type(n)#numpy.ndarray 数据.多维数组 
# display(n,type(n))#显示方式不是 python 标准的打不出来
#07 - Numpy聚合操作
n1=npy.ones(shape=(3,4))
# print("Numpy聚合操作-1\n",n1)
'''
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
'''
n2 = npy.ones(shape=(3,),dtype=npy.int64)#dtype数据类型
# print("Numpy聚合操作-2\n",n2)
n3 = npy.zeros((5,5), dtype=npy.int64)
# print("Numpy聚合操作-3\n",n3)
''' 
[[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]]
'''
n4=npy.full((4,5),10)#完整的
# print("Numpy聚合操作-4\n",n4)
'''
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
'''
n5=npy.eye(3,3)
# print("Numpy聚合操作-5\n",n5)
'''
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
'''
n6=npy.arange(10)
# print("Numpy聚合操作-6\n",n6)
'''
 [0 1 2 3 4 5 6 7 8 9]
'''
n7=npy.random.randint(1,10,size=(3,4))
# print("Numpy聚合操作-7\n",n7)
'''
Numpy聚合操作-7
 [[8 1 8 6]
 [4 3 8 1]
 [2 8 2 4]]
'''
n8=npy.random.normal(10, 5, size=(3,4))#其元素是从正态分布中随机抽取的。这个正态分布的平均值（mean）为 10，标准差（standard deviation）为 5。
# print("Numpy聚合操作-8\n",n8)
'''
    生成一个形状为 3x4 的数组
 [[12.88975749  6.85738122 14.80566481 15.46966296]
 [19.05942045  7.01871961 19.5368051  15.4231615 ]
 [ 9.31041488 11.50846991 13.65594234 18.39104925]]
'''

'''
平均值：

方差：方差越大，数据波动性越大

标准差：方差开平方

班级1：100,100,10 ---->平均值：70分
班级2  70  70 70------>平均值：70分
'''
n9 = npy.random.random(size=(3,4))
# print("Numpy聚合操作-9\n",n9)# [0.0, 1.0) 区间 即包括 0.0 但不包括 1.0。
n10=npy.random.randint(1,10,size=(3,4,5))
# print("Numpy聚合操作-10\n",n10)
'''
Numpy聚合操作-10
 [[[4 5 5 1 6]
  [2 8 4 9 1]
  [8 1 2 4 4]
  [2 7 4 2 4]]

 [[4 4 2 3 7]
  [8 1 2 5 8]
  [6 5 5 4 1]
  [7 2 5 5 4]]

 [[3 9 2 5 6]
  [6 1 8 8 8]
  [2 7 7 3 8]
  [2 9 4 2 1]]]
'''

# n10_1=npy.random.randint(1,10,size=(1,1,5))
# print("Numpy聚合操作-10\n",n10_1)# [[[7 6 1 8 9]]]
# n10_1=npy.random.randint(1,10,size=(3,2,1))
# n10_1=npy.random.randint(1,10,size=(数组的个数,列,数))
# print("Numpy聚合操作-10\n",n10_1)
'''
 [[[9 2 9 4 7]
  [4 6 7 4 6]]]
'''
n11_1=n.shape#返回其形状
#形状是一个只含有一个元素的元组，表示数组的长度；
# print(n11_1)
#(4,)

n_1=npy.array([[1,2,3,4],[5,6,7,8]])#二维数组
n11=n_1.shape#返回其形状
#对于二维数组（例如矩阵），形状是一个包含两个元素的元组，
# print(n11)
#(2, 4)

# print("一维数组的",n.size)
# 一维数组的 4

# print("二维数组的",n_1.size)
# 二维数组的 8
n12=npy.arange(10)
print(n12)

#8 - Numpy的矩阵操作



#9 - 认识Series


#10 - Series的运算




In [ ]:
import  numpy as np
n = np.random.randint(0,10, size=(4,5))
print("原来的+\n",n)
print("加\n",n + 1 ) # 加
print("减\n", n - 1 ) # 减
print("乘\n", n * 2 ) # 乘
print("除\n", n / 2 ) # 除
print("整除\n", n // 2)  # 整除
print(" 余数\n", n % 2 ) # 余数
    

In [ ]:
import  numpy as np
n = np.array([1, 4, 8, 9, 16, 25,0])
print("累加",np.cumsum(n)) # 计算累加和
print("排序",np.sort(n))
np.abs(n) # 绝对值
np.sqrt(n) # 开平方
np.square(n) # 平方
np.exp(n) # 指数
np.log(n) # 自然对数,以e为底的对数
np.round(n) # 四舍五入
np.ceil(n) # 向上取整
np.floor(n) # 向下取整
n1_1 = np.random.randint(0, 10, size=(2,3))
n2_1 = np.random.randint(0, 10, size=(3,4))
display("^v^",n1_1,"===",n2_1)
# 行和列 保持一样的个数
# 矩阵乘积---求和（行*列）
np.dot(n1_1,n2_1)


In [ ]:
n2 = np.random.randint(0, 10, size=(3,4))
print("原数据\n",n2)
n2=np.sort(n2,axis=1)
n2_1=np.sort(n2,axis=1)
print("根据横向排序\n",n2_1)
n2=np.sort(n2,axis=0)
n2_2=np.sort(n2,axis=0)
print("根据纵向排序\n",n2_2)
print("排序后\n", n2)

np.savetxt("t.csv",n2,delimiter=",")
print("读取的数据===\n",np.loadtxt("t.csv",delimiter=","))


In [ ]:
#广播机制
mm = np.ones((2,3), dtype=int)
aa = np.arange(3)
display(mm, aa)
a = np.arange(3).reshape((3,1))#矩阵变维
b = np.arange(3)
display(a, b)

In [61]:
import numpy as nmp
import pandas as pd
from pandas import Series
# l = [1,2,3,4]
# s = Series(l)
# s
# 认识Series.ipynb


n = np.random.randint(1,10,size=(6,))
n
s = Series(n)
s
s.index
list(s.index)
# s.values

[0, 1, 2, 3, 4, 5]

In [73]:
n = np.random.randint(1, 10, size=(3,))
s = pd.Series(n)
s.index = ["a", "b", "c"]
print("t1===\n",n)
print("t2===\n",s)
print("# 隐式索引\n", s.iloc[0])
print("# 显示索引\n", s.loc["a"])
print("# 特殊语法\n", s["a"])
print("# 特殊语法\n", s.a)


t1===
 [6 6 5]
t2===
 a    6
b    6
c    5
dtype: int32
# 隐式索引
 6
# 显示索引
 6
# 特殊语法
 6
# 特殊语法
 6


In [ ]:
#缺失值的处理

#02-DataFrame的运算

#03-多层次索引



#01 - Pip介绍

#01-认识DataFrame

# day6

In [ ]:
import pandas as pd
t1=pd.read_csv("E:///python代码/rk1/data/data.csv")





In [74]:
# t1_1=t1.to_csv("E:///python代码/rk1/data/data1.csv")
t1_2=pd.read_table("../data/data1.csv",sep=",",index_col=[0])
print(t1_2)







    Name   Age      City  Salary
0   John  25.0  New York  5000.0
1  Alice  30.0    London  6000.0
2    Bob   NaN     Paris     NaN
3   Jane  35.0     Tokyo  7000.0
4   Mike  27.0    Sydney  5200.0
5   Lisa  32.0    Berlin  6200.0
6    Tom  29.0      Rome     NaN
7   Emma   NaN   Toronto  6800.0
8   Alex  26.0    Moscow  4800.0
9   Kate  31.0     Dubai  5800.0
