In [ ]:
import numpy as py
py.array()
py.argmax()
py.argmin()
py.bincount()
py.ones()
py.sort()
py.max
py.min
py.reshape()
py.ravel()
py.linspace()
py.loadtxt()
py.zeros()
py.sum()
py.append()
py.split()
py.full()
py.mean()
py.size()

 #以下是对这些`numpy`函数的介绍：
# 
# 1. `import numpy as py`：这是导入方式，其`numpy`是一个强大的科学计算库，用于处理多维数组和矩阵运算等。
# 2. `np.array()`：用于创建一个`numpy`数组，可以从列表、元组等可迭代对象创建数组。

# 3. `np.argmax()`：返回数组中最大值的索引。如果是多维数组，可以指定轴来沿着特定维度查找最大值索引。
# 
# 4. `np.argmin()`：返回数组中最小值的索引，类似`np.argmax()`。
# 
# 5. `np.bincount()`：统计非负整数数组中每个值的出现次数。
# 
# 6. `np.ones()`：创建一个全为 1 的数组，可以指定形状。
# 
# 7. `np.sort()`：对数组进行排序，可以指定轴和排序算法。
# 
# 8. `np.max`：返回数组中的最大值，可以指定轴。
# 
# 9. `np.min`：返回数组中的最小值，类似`np.max`。
# 
# 10. `np.reshape()`：改变数组的形状，例如将一维数组变为二维数组等。
# 
# 11. `np.ravel()`：将多维数组展平为一维数组。
# 
# 12. `np.linspace()`：在指定范围内生成等间隔的数字序列。
# 
# 13. `np.loadtxt()`：从文本文件中读取数据并创建数组。
# 
# 14. `np.zeros()`：创建一个全为 0 的数组，可以指定形状。
# 
# 15. `np.sum()`：计算数组中所有元素的和，可以指定轴。
# 
# 16. `np.append()`：向数组中添加元素，可以在末尾或指定位置添加。
# 
# 17. `np.split()`：将数组分割成多个子数组。
# 
# 18. `np.full()`：创建一个具有指定形状和填充值的数组。
# 
# 19. `np.mean()`：计算数组的平均值，可以指定轴。
# 
# 20. `np.size()`：返回数组中元素的总数。

In [2]:
#TODO：======================用法======================
import numpy as np

# np.array()
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)


[1 2 3 4]


In [3]:

# np.argmax() 和 np.argmin()
arr = np.array([5, 2, 8, 1])
print(np.argmax(arr))
print(np.argmin(arr))

2
3


In [4]:


# np.bincount()
arr = np.array([1, 1, 2, 3, 3])
print(np.bincount(arr))

[0 2 1 2]


In [5]:

# np.ones()
ones_arr = np.ones((3, 4))
print(ones_arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:

# np.sort()
arr = np.array([4, 2, 6, 1])
sorted_arr = np.sort(arr)
print(sorted_arr)



[1 2 4 6]


In [7]:
# np.max 和 np.min
arr = np.array([3, 7, 2, 9])
print(np.max(arr))
print(np.min(arr))



9
2


In [8]:
# np.reshape()
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)



[[1 2 3]
 [4 5 6]]


In [9]:

# np.ravel()
arr = np.array([[1, 2], [3, 4]])
flattened_arr = np.ravel(arr)
print(flattened_arr)



[1 2 3 4]


In [10]:


# np.linspace()
linspace_arr = np.linspace(0, 10, 5)
print(linspace_arr)



[ 0.   2.5  5.   7.5 10. ]


In [11]:


# np.loadtxt()
# 假设存在一个文本文件 data.txt，内容为：1 2 3\n4 5 6
data = np.loadtxt('data.txt')
print(data)




FileNotFoundError: data.txt not found.

In [12]:



# np.zeros()
zeros_arr = np.zeros((2, 3))
print(zeros_arr)




[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:


# np.sum()
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))



10


In [14]:


# np.append()
arr = np.array([1, 2, 3])
new_arr = np.append(arr, 4)
print(new_arr)




[1 2 3 4]


In [15]:



# np.append()
arr = np.array([1, 2, 3])
new_arr = np.append(arr, 4)
print(new_arr)




[1 2 3 4]


In [16]:


# np.full()
full_arr = np.full((2, 3), 5)
print(full_arr)



[[5 5 5]
 [5 5 5]]


In [17]:


# np.mean()
arr = np.array([2, 4, 6])
print(np.mean(arr))


4.0


In [18]:

# np.size()
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.size(arr))


6
